export const GOOGLE_CLIENT_ID = process.env.REACT_APP_GOOGLE_CLIENT_ID;

export const SERVER_ENDPOINT = process.env.REACT_APP_SERVER_ENDPOINT;

export const OAUTH_REDIRECT_URL = process.env.REACT_APP_OAUTH_REDIRECT_URL;
